tasks:
  build:
    image: alekzonder/puppeteer:1.8.0-0
    command:
      - yarn
    args:
      - install
  lint:
    image: alekzonder/puppeteer:1.8.0-0
    command:
      - yarn
    args:
      - lint
  test:
    image: alekzonder/puppeteer:1.8.0-0
    command:
      - yarn
    args:
      - test
